### ISSUE TITLE
shape should be a property, not a method

### ISSUE THREAD

**Issue by shoyer** [michelemartone/pyrsb#1]
This looks like an interesting project!

In your examples, I noticed you have:

    nr=a.shape()[0]
    nc=a.shape()[1]

For consistency with scipy.sparse, this should be:

    nr=a.shape[0]
    nc=a.shape[1]

I think you just need to add the `@property` decorator to your sparse matrix class.

**Comment by michelemartone** [comment]
Thanks Stephan! I just corrected as you suggested.
