### ISSUE TITLE
Error Demo

### ISSUE THREAD

**Issue by mbarbry** [michelemartone/pyrsb#2]
Hello Michele,

I'm Marc, we exchanged a coupled of emails some days ago on scipy email list.
Finally, intelPython is not giving that good performance for sparse matrix operations.

So I decided to look again to your program. I managed to compile the code after a bit of modifications in the setup file, somehow it was mixing my python2 and python3 library. Here, is my modified version,

```python
from distutils.core import setup
from distutils.extension import Extension
from Cython.Distutils import build_ext
from Cython.Build import cythonize

ext_modules = [
        Extension("rsb", ["rsb.pyx"],
            libraries=["rsb","z","hwloc"])]
setup(
    name = 'rsb',
    cmdclass = {'build_ext': build_ext},
    ext_modules = cythonize(ext_modules)
)
```

The code is compiling fine, but the demo script failed after a few tests,
```bash
python demo.py 
  (0, 0)	11.0
  (0, 1)	12.0
  (1, 1)	22.0
Traceback (most recent call last):
  File "demo.py", line 15, in <module>
    print(a)
  File "rsb.pyx", line 189, in rsb.rsb_matrix.__str__ (rsb.c:4767)
    return "["+buf+"]"
TypeError: Can't convert 'bytes' object to str implicitly
```

Do you know if this is a bug of your program or a problem with my installation?

Best regards,
Marc

**Comment by mbarbry** [comment]
ok, seems to be an issue with python3. Your code is not tested against python3?

**Comment by michelemartone** [comment]
Hi Marc,
sorry for the super-late response.
Last May comments should have fixed all of those problems :-)
