### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by mbarbry** [michelemartone/pyrsb#4]
Hi Michele,

I tried to compile pyrsb, but I'm getting a compilation error (both docker and local give the same errors).

Best regards,
Marc

    Step 13/13 : RUN make
     ---> Running in 37ba4898290e
    gcc -I/usr/include/ -I/usr/include/python3.7m -I/usr/include/python3.7m  -Wno-unused-result -Wsign-compare -g -fdebug-prefix-map=/build/python3.7-neQ7kp/python3.7-3.7.6=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector -Wformat -Werror=format-security  -DNDEBUG -g -fwrapv -O3 -Wall    -c -o rsb.o rsb.c
    In file included from /usr/include/python3.7m/numpy/ndarraytypes.h:1830,
                     from /usr/include/python3.7m/numpy/ndarrayobject.h:12,
                     from /usr/include/python3.7m/numpy/arrayobject.h:4,
                     from rsb.c:486:
    /usr/include/python3.7m/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
       17 | #warning "Using deprecated NumPy API, disable it with " \
          |  ^~~~~~~
    rsb.c: In function '__pyx_pf_3rsb_10rsb_matrix_44_find_block':
    rsb.c:8263:69: warning: passing argument 2 of 'rsb_mtx_get_coo_block' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
     8263 |   __pyx_v_self->errval = rsb_mtx_get_coo_block(__pyx_v_self->mtxAp, __pyx_v_VA, __pyx_v_IA, __pyx_v_JA, __pyx_t_4, __pyx_t_3, __pyx_t_2, __pyx_t_1, NULL, NULL, NULL, RSB_FLAG_NOFLAGS);
          |                                                                     ^~~~~~~~~~
    In file included from rsb.c:482:
    /usr/include/rsb.h:835:71: note: expected 'void *' but argument is of type 'const void *'
      835 | rsb_err_t rsb_mtx_get_coo_block(const struct rsb_mtx_t * mtxAp, void* VA, rsb_coo_idx_t * IA, rsb_coo_idx_t * JA, rsb_coo_idx_t frA, rsb_coo_idx_t lrA, rsb_coo_idx_t fcA, rsb_coo_idx_t lcA, rsb_coo_idx_t * IREN, rsb_coo_idx_t * JREN, rsb_nnz_idx_t *rnzp, rsb_flags_t flags );
          |                                                                 ~~~~~~^~
    rsb.c: In function '__pyx_pf_3rsb_10rsb_matrix_50find':
    rsb.c:8829:63: warning: passing argument 2 of 'rsb_mtx_get_coo' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
     8829 |   __pyx_v_self->errval = rsb_mtx_get_coo(__pyx_v_self->mtxAp, __pyx_v_VA, __pyx_v_IA, __pyx_v_JA, RSB_FLAG_NOFLAGS);
          |                                                               ^~~~~~~~~~
    In file included from rsb.c:482:
    /usr/include/rsb.h:832:66: note: expected 'void *' but argument is of type 'const void *'
      832 | rsb_err_t rsb_mtx_get_coo(const struct rsb_mtx_t * mtxAp, void * VA, rsb_coo_idx_t * IA, rsb_coo_idx_t * JA, rsb_flags_t flags );
          |                                                           ~~~~~~~^~
    rsb.c: In function '__Pyx__ExceptionSave':
    rsb.c:16347:21: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_type'; did you mean 'curexc_type'?
    16347 |     *type = tstate->exc_type;
          |                     ^~~~~~~~
          |                     curexc_type
    rsb.c:16348:22: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_value'; did you mean 'curexc_value'?
    16348 |     *value = tstate->exc_value;
          |                      ^~~~~~~~~
          |                      curexc_value
    rsb.c:16349:19: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
    16349 |     *tb = tstate->exc_traceback;
          |                   ^~~~~~~~~~~~~
          |                   curexc_traceback
    rsb.c: In function '__Pyx__ExceptionReset':
    rsb.c:16356:24: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_type'; did you mean 'curexc_type'?
    16356 |     tmp_type = tstate->exc_type;
          |                        ^~~~~~~~
          |                        curexc_type
    rsb.c:16357:25: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_value'; did you mean 'curexc_value'?
    16357 |     tmp_value = tstate->exc_value;
          |                         ^~~~~~~~~
          |                         curexc_value
    rsb.c:16358:22: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
    16358 |     tmp_tb = tstate->exc_traceback;
          |                      ^~~~~~~~~~~~~
          |                      curexc_traceback
    rsb.c:16359:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_type'; did you mean 'curexc_type'?
    16359 |     tstate->exc_type = type;
          |             ^~~~~~~~
          |             curexc_type
    rsb.c:16360:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_value'; did you mean 'curexc_value'?
    16360 |     tstate->exc_value = value;
          |             ^~~~~~~~~
          |             curexc_value
    rsb.c:16361:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
    16361 |     tstate->exc_traceback = tb;
          |             ^~~~~~~~~~~~~
          |             curexc_traceback
    rsb.c: In function '__Pyx__GetException':
    rsb.c:16416:24: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_type'; did you mean 'curexc_type'?
    16416 |     tmp_type = tstate->exc_type;
          |                        ^~~~~~~~
          |                        curexc_type
    rsb.c:16417:25: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_value'; did you mean 'curexc_value'?
    16417 |     tmp_value = tstate->exc_value;
          |                         ^~~~~~~~~
          |                         curexc_value
    rsb.c:16418:22: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
    16418 |     tmp_tb = tstate->exc_traceback;
          |                      ^~~~~~~~~~~~~
          |                      curexc_traceback
    rsb.c:16419:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_type'; did you mean 'curexc_type'?
    16419 |     tstate->exc_type = local_type;
          |             ^~~~~~~~
          |             curexc_type
    rsb.c:16420:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_value'; did you mean 'curexc_value'?
    16420 |     tstate->exc_value = local_value;
          |             ^~~~~~~~~
          |             curexc_value
    rsb.c:16421:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
    16421 |     tstate->exc_traceback = local_tb;
          |             ^~~~~~~~~~~~~
          |             curexc_traceback
    make: *** [<builtin>: rsb.o] Error 1
    The command '/bin/sh -c make' returned a non-zero code: 2

**Comment by michelemartone** [comment]
Hi Marc, thanks for the feedback.

I just tried the Docker image and laptop as well (which uses /usr/include/python3.7m, as you), but I experience no problems.

Are you able to suggest a fix, so that I may somehow combine it ?
Or maybe can you clone the repo and suggest me a Travis setup where it fails ?

**Comment by mbarbry** [comment]
Hi Michele,

Installing pyrsb in a clean virtualbox worked properly.
Probably some conflict in my local environment. But it is odd that the Dockerfile failed as well.

Did you already tried to install pyrsb in a Anaconda environment?

**Comment by michelemartone** [comment]
Hi Marc,

I did not --- would you be willing to give me some help with that?

**Comment by mbarbry** [comment]
I will definitively give it a try.
