### ISSUE TITLE
AttributeError: 'rsb.rsb_matrix' object has no attribute 'nrA'

### ISSUE THREAD

**Issue by mbarbry** [michelemartone/pyrsb#5]
Hi Michele,

I managed to install properly pyrsb.
I tried the example of the README, and it worked well. However, when I tried another matrix, I get the following error

    AttributeError: 'rsb.rsb_matrix' object has no attribute 'nrA'

I attached the script that produces the error with a pickle file containing the matrix in COO format.

Any idea what is the origin of the problem?

Marc

[rsb_test.zip](https://github.com/michelemartone/pyrsb/files/4066899/rsb_test.zip)

**Comment by michelemartone** [comment]
The README file had indeed a slightly different vector type.
Can you please check the newest version out?

**Comment by mbarbry** [comment]
Seems to work, thanks!

Unfortunately, for this matrix, librsb is slower than scipy for matrix vector products, 0.0015 s per operation for librsb, versus 0.0006 s for scipy (with CSR format).

Any idea if it is possible to improve the performance?

**Comment by michelemartone** [comment]
Your matrix is very small and wide (2982 x 23104, 627882 nnz),  -- it fits in the cache -- not really the target of librsb at this point.
Do you happen to have larger matrices than this?
And, how many multiplication iterations do you foresee?
Once in production, do you multiply by one or many right hand sides?
How many cores and which cache size do you have ?
All the above matter, in addition to the sheer matrix size.
:-)

**Comment by michelemartone** [comment]
There's more to it -- If you use y=y+A*x then a copy of y occurs (=slowdown).
Using _spmv and _spmv directly avoids that copy.
Or other details, but that's outside the scope of this ticket, that we can move the performance thread to another channel.
