### ISSUE TITLE
path of libsrb

### ISSUE THREAD

**Issue by piskunow** [michelemartone/pyrsb#9]
When `make`, it is necessary that the path of `libsrb/bin` is accesible.

This is not clear from the instructions, it is not suggested nor requested during installation.

**Comment by michelemartone** [comment]
if you use ubuntu or debian, apt-get install librsb-dev.

**Comment by piskunow** [comment]
Why is the issue closed?

I understand that you want contributors to contribute.

I understand that the workflow for git issues is to report a problem or propose a feature. Have a discussion, and close it after realising is impractical, or after making a commit that fixes the issue.  

I see neither happening here.

What is the workflow you propose?

**Comment by michelemartone** [comment]
I reopened the issue.
Pyrsb assumes you have librsb installed.
Given the huge number of Debian/Ubuntu users, I added a note in the README.md with the notice of using apt-get to install librsb.
What more do you suggest?

**Comment by piskunow** [comment]
I think adding the required installs is enough for now.

I didn't notice the commit to change `README.md`. You can mention issue numbers in the commit like `Fix #9` or something like that. Then, the relevant commit appears here and the closing of the issue is transparent.

**Comment by michelemartone** [comment]
That may help. Good suggestion, thanks.
